//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suteki.TardisBank.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suteki.TardisBank.Web.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action can not be undone..
        /// </summary>
        public static string ActionCanNotBeUndone {
            get {
                return ResourceManager.GetString("ActionCanNotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer your account.
        /// </summary>
        public static string AdministerYourAccount {
            get {
                return ResourceManager.GetString("AdministerYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to your account.
        /// </summary>
        public static string BackToYourAccount {
            get {
                return ResourceManager.GetString("BackToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete your account, including your children&apos;s accounts, click the button below..
        /// </summary>
        public static string DeleteAccountPresentation {
            get {
                return ResourceManager.GetString("DeleteAccountPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes I&apos;m sure. Delete my account.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete My Account.
        /// </summary>
        public static string DeleteMyAccount {
            get {
                return ResourceManager.GetString("DeleteMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Account Summary.
        /// </summary>
        public static string FormatAccountSummary {
            get {
                return ResourceManager.GetString("FormatAccountSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Account.
        /// </summary>
        public static string FormatChildAccount {
            get {
                return ResourceManager.GetString("FormatChildAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Payment to {0}.
        /// </summary>
        public static string FormatMakeAPaymentTo {
            get {
                return ResourceManager.GetString("FormatMakeAPaymentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have transferred {0} to {1}&apos;s account with the description &quot;{2}&quot;..
        /// </summary>
        public static string FormatPaymentConfirmedMessage {
            get {
                return ResourceManager.GetString("FormatPaymentConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message has been sent to your parent asking for the amount of {0}. Ask them to check their messages..
        /// </summary>
        public static string FormatWithdrawlConfirmedMessage {
            get {
                return ResourceManager.GetString("FormatWithdrawlConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Payment.
        /// </summary>
        public static string MakeAPayment {
            get {
                return ResourceManager.GetString("MakeAPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Payment.
        /// </summary>
        public static string MakePayment {
            get {
                return ResourceManager.GetString("MakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pocket money schedule has been created yet..
        /// </summary>
        public static string NoPocketMoneySchedule {
            get {
                return ResourceManager.GetString("NoPocketMoneySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no transactions yet..
        /// </summary>
        public static string NoTransactions {
            get {
                return ResourceManager.GetString("NoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmed.
        /// </summary>
        public static string PaymentConfirmed {
            get {
                return ResourceManager.GetString("PaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Description.
        /// </summary>
        public static string PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket Money Schedule.
        /// </summary>
        public static string PocketMoneySchedule {
            get {
                return ResourceManager.GetString("PocketMoneySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up Schedule.
        /// </summary>
        public static string SetUpSchedule {
            get {
                return ResourceManager.GetString("SetUpSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A free, online, pocket money bank account for parents and kids..
        /// </summary>
        public static string WebsiteDescription {
            get {
                return ResourceManager.GetString("WebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket money on-line banking for kids and parents.
        /// </summary>
        public static string WebsiteSubtitle {
            get {
                return ResourceManager.GetString("WebsiteSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tardis Bank.
        /// </summary>
        public static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Cash.
        /// </summary>
        public static string WithdrawCash {
            get {
                return ResourceManager.GetString("WithdrawCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawl Confirmed.
        /// </summary>
        public static string WithdrawlConfirmed {
            get {
                return ResourceManager.GetString("WithdrawlConfirmed", resourceCulture);
            }
        }
    }
}
