//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suteki.TardisBank.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suteki.TardisBank.Web.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have transferred {0} to {1]&apos;s account with the description &quot;{2}&quot;..
        /// </summary>
        public static string FormatPaymentConfirmedMessage {
            get {
                return ResourceManager.GetString("FormatPaymentConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Payment.
        /// </summary>
        public static string MakePayment {
            get {
                return ResourceManager.GetString("MakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmed.
        /// </summary>
        public static string PaymentConfirmed {
            get {
                return ResourceManager.GetString("PaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Description.
        /// </summary>
        public static string PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A free, online, pocket money bank account for parents and kids..
        /// </summary>
        public static string WebsiteDescription {
            get {
                return ResourceManager.GetString("WebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket money on-line banking for kids and parents.
        /// </summary>
        public static string WebsiteSubtitle {
            get {
                return ResourceManager.GetString("WebsiteSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tardis Bank.
        /// </summary>
        public static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
    }
}
